# Generated by Django 5.2.6 on 2025-09-15 13:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Harga')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=225)),
                ('stok', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
